name: DevSecOps Sentinel Pipeline

on: [push, pull_request]

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Python Static Analysis (Bandit)
        run: |
          pip install bandit
          bandit -r . -f txt || true

      - name: Scan Container for CVEs (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python:3.11-slim'
          format: 'table'
          severity: 'CRITICAL,HIGH'
